### ISSUE TITLE
path?

### ISSUE THREAD

**Issue by pmb123** [cralor/TomTomVanilla#1]
I installed and it's not showing up in the addon selection screen.  Folder is named TomTomVanilla.  What am I doing wrong?  Permissions appear to be the same as other addons.

**Comment by cralor** [comment]
The folder name should be 'TomTom' within the AddOns folder.

I didn't necessarily think about this... perhaps it is worth renaming the AddOn itself 'TomTomVanilla' to avoid confusion. What do you think?

The bottom line is that the folder name should match the AddOn's name. Let me know how this works out for you.

**Comment by cralor** [comment]
I'll add some clarifying instructions to the release page to ensure this is more clear. Thanks for your feedback!
